- .github/CONTRIBUTING.md
Added a branch schema description in the CONTRIBUTING.md file.
NA
* concerns 
* an outline of threats and risks and how they are being addressed.
NA
What kind of change does this Pull Request …
> Update CONTRIBUTING.md with the branch schema

- R/output_table.R
- R/tree_segment.R
Fixed error in substr bug
- [x ] 📝 The commit message is clear and descriptive
- [ x] 🔐 The Security Considerations section in the PR description is complete - **Please do not remove this**
- [ x] ✅ Tests for the changes have been added and run successfully including the new changes
- [ x] 📄 Documentation has been added / updated (for bug fixes / features)
NA
**Does this PR introduce a breaking change?** (What changes might users need …
> Fixed error in substr bug

- R/segment.R
- README.md
Hyperparameters now update a default list when passed. So all, some or no hyperparameters can be passed and the function will still work. Also fixes print plot bug.
* concerns 
* an outline of …
> Change default hyperparameter behaviour

- .github/workflows/os-x.yml
Updating docs branch to be up to date with main
* concerns 
* an outline of threats and risks and how they are …
> Updating docs branch to be up to date with main

- .github/workflows/os-x.yml
- .github/workflows/r_new.yml
Both workflows are named "CI-CD" on the Actions page, updated the names to differentiate between them.
* concerns 
* an outline of threats and risks …
> Workflows name update

- vignettes/Tree.Rmd
Added tree vignette
What kind of change does this Pull Request introduce?
_Put an `x` in the boxes that apply_
Please include steps that the reviewer can follow in order to test the changes
1.`pkgdown::build_site()` requires running and checking if it works on the website
> added tree vignette

- R/output_table.R
- R/unsupervised_segment.R
- R/validate.R
Fixing error in unsupervised function: when passing a list of segmentation variables it raises an error if the "customerid" is not included in the list.
NA
* concerns 
* an outline of threats …
> Fix customerid error in unsupervised function 

- R/segment.R
- R/unsupervised_segment.R
- tests/testthat/test_validate.R
- Updated unit tests with the hyperparameters argument.
- Changed the position of the validate() function so that it doesn't use the default params when the user has passed custom parameters
- Added na.rm statements to two function which seemed to be causing issues with NA values
Please check if the PR fulfils these requirements:
Please discuss the security implications/considerations relevant to the proposed change. …
> Updating unit tests and adding na.rm to calculations

- R/validate.R
Added a step in validate to stop the run if infinite values are present, these could be imputed or removed by preprocessing step if required
What kind of change does this Pull Request introduce?
_Put an `x` in the boxes that apply_
Please include steps that the reviewer can follow in order to test the changes
1. Run the following code to see an error when Infinite values are present 
``` …
```
> Added Infinite bug fix

- R/unsupervised_segment.R
fixes https://app.asana.com/0/1199194792220883/1200863218432364/f 
This references `customerid` so will need to be update when this get changed.  …
> fix segmentation variables bug

- vignettes/Preprocessing.Rmd
- vignettes/citrus.Rmd
Updating preprocessing documentation
NA
* concerns 
* implementation-specific …
> Updating preprocessing documentation

- R/preprocess.R
- R/unsupervised_segment.R
Description of what this PR does. What have you added or changed, and why? If it fixes a bug or resolves a feature request, be sure to link to that issue.
Fixed Selections can't have missing values Bug
What kind of change does this Pull Request introduce?
_Put an `x` in the boxes that apply_
Please include steps that the reviewer can follow in order to test the changes
formatted <- preprocess(citrus::transactional_data, target = NA)
or run preprocess with target = NA with any other data set.
This should now take into account categorical features …
> Fixed "Selections can't have missing values" Bug

- R/output_table.R
- R/unsupervised_segment.R
- R/validate.R
Replaced the deprecated functions `funs()` and `summarise_each()`. 
`funs()` is just a way to list function names which was built into `list()` with the new dplyr update. Because of the way we replaced `summarise_each()` below, it wasn't needed in the new version of the code.
`summarise_each()` summarises all the columns in a DF based on a condition, and the function that would be used would also depend on a condition. In this instance, the conditions is supposed to be `is.numeric`. In order to replace this functionality, the table was split into two from the start, one with numeric and one with non-numeric columns. We can then just run `summarise()` over all the columns in each DF and simply re-join the resulting DFs at the end to end up with the same table as before.
Please check if the …
> Replace deprecated functions

- tests/testthat/test_segment.R
Updating the expected columns of the output table to 11.
* concerns 
* an outline of threats and risks and how they are being addressed.
**YOUR TEXT …
> Update unit tests

- tests/testthat/test_segment.R
**YOUR TEXT HERE**
* concerns 
* …
> Reversing unit test change

- R/segment.R
- man/segment.Rd
Naming the allowed values of the modeltype and steps parameters. The function will raise an error if the argument passed is not one of the allowed values. 
* concerns 
* implementation-specific …
> Enforcing modeltype and steps argument values

- .Rbuildignore
- cran-comments.md
File with comments for the CRAN reviewers. Contains the test environments used and the R CMD Check results.
* concerns 
* an outline of threats and …
> cran-comments.md for CRAN submission

- R/segment.R
The segment function currently only allows a single step value to be passed, but multiple must be allowed. several.ok = TRUE solves that.
* concerns  …
> Allowing multiple steps to be passed for "steps" argument

- R/model_management.R
- R/output_table.R
- R/preprocess.R
- R/segment.R
- R/tree_segment.R
- R/unsupervised_segment.R
Replaced all T's with TRUE and F's with FALSE.
**YOUR TEXT HERE**
- [x ] 📝 The commit message is clear and descriptive
- [x ] 🔐 The Security Considerations section in the PR description is complete - **Please do not remove this**
- [x ] ✅ Tests for the changes have been added and run successfully including the new changes
Please discuss the security …
> True or False edits.

- R/preprocess.R
- R/segment.R
- R/tree_segment.R
- R/unsupervised_segment.R
Replaced prints with appropriate warnings and messages. Also defaulted verbose to FALSE rather than TRUE.
* concerns 
* an outline of threats and …
> Replaced prints and set verbose to FALSE

- R/model_management.R
- R/output_table.R
- R/plotting.R
- R/preprocess.R
- R/segment.R
- R/tree_segment.R
- R/unsupervised_segment.R
- R/validate.R
- man/citrus_pair_plot.Rd
- man/k_clusters.Rd
- man/model_management.Rd
- man/output_table.Rd
- man/preprocess.Rd
- man/rpart.plot_pretty.Rd
- man/segment.Rd
- man/tree_abstract.Rd
- man/tree_segment.Rd
- man/tree_segment_prettify.Rd
- man/validate.Rd
Added a description of return values for all user functions in the package and rerun `roxygenise`.
* concerns 
* an outline of threats and risks and …
> Setting "return" descriptions for roxygen documentation.

- cran-comments.md
- tests/testthat/test_output_table.R
Set the `saveoutput` argument to FALSE in our unit tests.
Also added the required CRAN comments to the cran-comments.md file for the CRAN re-submission.
* concerns 
* implementation-specific …
> saveoutput to FALSE in unit tests + cran-comments.md additions

- DESCRIPTION
- R/tree_segment.R
- man/tree_segment.Rd
Adding Stu as author in the package DESCRIPTION and relevant functions.
* concerns 
* an outline of threats and risks and how they are being …
> Adding Stu as author

- DESCRIPTION
Defines the version requirements for all imported packages. I've done this both by looking at what point the latest addition/bugfix/change was made to a function used, as well as by simply looking at what version works in the Peak workspaces that also isn't too recent.
This may …
> Package version reqs

- R/output_table.R
There is an error in the output_table() function when the segmentation features are all only character or numeric columns. 
In the function the customer table is split into a data.frame for each variable type. If the data.frame for one of the types hasn't got any columns other than the "segment" label column then the data.frame, incorrectly, gets parsed as a vector, causing the error. This PR fixes that.
Please check if the PR fulfils these requirements:
Are there any other …
> Stop data frames to be parsed as vectors when only a single column is selected

- DESCRIPTION
**YOUR TEXT HERE**
* concerns 
* …
> Update dplyr version req.

- R/preprocess.R
Added a line that changes categorical features to factors with levels the same as the full data set
* …
> Added factors to fix the newlevels issue

- R/segment.R
- R/tree_segment.R
- R/unsupervised_segment.R
The current output object include the input_data used to train the model. This seems unnecessary and may caused unexpected memory issues for the user. This fix removes the input_data object from the output.
* concerns 
* …
> Removing input_data object from output object

- R/segment.R
The segment() function falls over if the only step passed is the "preprocess" step. This fix makes the segment() function just return the preprocessed data immediately if it is the only step passed to the function.
* …
> Returning preprocessed data immediately if it's the only step passed

- R/unsupervised_segment.R
The model_hyperparameters variable does not contain the standardize argument. This fix adds it.
* concerns 
* an outline of threats and risks and how …
> Adding standardize argument to hyperparam output objecT

- R/output_table.R
Fixed bug on column names in output table. Correct labels (_mode and _top5) are now assigned to the columns referring to character data when creating the output table.
This was originally a fix by Cinzia, but I (Oskar) messed up the commit signing so had to redo it.
This may …
> Correctly labels output table columns

- tests/testthat/test_output_table.R
- tests/testthat/test_segment.R
Updated unit tests to align with the 1.0.2 release.
* concerns 
* an outline of threats and risks and how they are being addressed.
**YOUR TEXT HERE** …
> Updated unit tests

- tests/testthat/test_output_table.R
- tests/testthat/test_segment.R
This is exactly the same PR as this one: https://github.com/peak-ai/CITRUS/pull/91#issue-1270583694
It was reverted when I merged v1.0.2 to `main`.
* concerns 
* implementation-specific guidance and …
> Updating unit tests
